[package]
name = "set5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto-bigint = "0.5.5"
num = "0.4.1"
num-bigint = "0.4.4"
num-traits = "0.2.17"
set1 = { path = "../set1"}
sha3 = "0.10.8"

